config/routes.rb
VotingTutorial::Application.routes.draw do
  root :to => 'questions#index'

  resources :questions

  match 'questions/:id/upvote' => 'questions#upvote', :as => :upvote
  match 'questions/:id/downvote' => 'questions#downvote', :as => :downvote

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title, :user_id

  validates :title, :presence => true
  validates_uniqueness_of :title

  belongs_to :parent
  belongs_to :user
  has_many :votes

  def vote(user)
    if self.votes.where(:user_id => user).present?
      return nil
    else
      self.votes << Vote.create(:user => user)
      true
    end
  end

  def downvote(user)
    if self.votes.where(:user_id => user).present?
      @vote = self.votes.where(:user_id => user)
      @vote.destroy_all
    else
      return nil
    end
  end

  def score()
    self.votes.count
  end

end 

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username
  
  has_many :questions
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  
  attr_accessible :user, :question

  belongs_to :question
  belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  def current_user
    @current_user = User.find(3)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
  
  def upvote
    @question_we_are_upvoting = Question.find(params[:id])
    @question_we_are_upvoting.vote(@current_user)
    redirect_to root_url
  end

  def downvote
    @question_we_are_downvoting = Question.find(params[:id])
    @question_we_are_downvoting.downvote(@current_user)
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @looked_up_user = User.find_by_id(@current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "VotingTutorial"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .brand
            = link_to("VotingApp", root_url)
          .container.nav-collapse
            %ul.nav

    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav          
        .span9
          = yield
    
      %footer
        %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/questions/_form.html.haml
= form_for @question do |f|
  -if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', @question
\|
= link_to 'Back', questions_path

app/views/questions/index.html.haml
%h1 
  Listing questions (
  = link_to 'New Question', new_question_path
  )
%br
%ul
  - @questions.each do |question|
    %li
      (
      = question.score
      )
      = question.title
      (
      = link_to "uVote", upvote_url(question), :method => :post
      \/
      = link_to "dVote", downvote_url(question), :method => :delete
      )

app/views/questions/new.html.haml
%h1 New question

= render 'form'

= link_to 'Back', questions_path

app/views/questions/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @question.title

= link_to 'Edit', edit_question_path(@question)
\|
= link_to 'Back', questions_path

app/views/users/show.html.haml
- @looked_up_user.votes.each do |vote|
  = vote.question_id